#+TITLE: NIKTO NOTE
#+DESCRIPTION: nikto web scanning tool
#+AUTHOR: Linux-DEX
#+OPTIONS: toc:4

* TABLE OF CONTENT :toc:
- [[#introduction][Introduction]]
- [[#commands][Commands]]

* Introduction
+ Nikto is an open source web server and web application scanner.
+ Nikto can perform comprehensive tests against web servers for multiple security threats, including over 6700 potentially dangerous file/ programs.
+ Nikto can also perform checks for outdated web servers software, and version-specific problems.

* Commands
1. *Help command for nikto*:
#+begin_example
$ nikto --help
#+end_example

2. *Scan a domain using =-h= (host) flag*:
#+begin_example
$ nikto -h scanme.nmap.org
#+end_example

3. *Scan a Domain with SSL Enabled*:
#+begin_example
$ nikto -h https://nmap.org -ssl
#+end_example

4. *Scan an IP Address*:
#+begin_example
$ nikto -h 45.33.32.123
#+end_example

5. *Scan multiple IP Address from a Text File*:
#+begin_example
$ nikto -h domains.txt
#+end_example

+ The text file should contain domain or ip address to scan.

6. *Save the Scan Result to file*:
#+begin_example
$ nikto -h scanme.nmap.org -o scan.txt
#+end_example

- can use =-Format= flag to specify an output format. example format csv, html, nbe, sql, txt,xml.
#+begin_example
$ nikto -h scanme.nmap.org -o scan.csv -Format csv
#+end_example

7. *Pair Nikto with metasploit*:
#+begin_example
$ nikto -h <domain/ip> -Format msf+
#+end_example

- append the =-Format msf+= flag to the end of a scan.
