#+TITLE: Password Manager
#+DESCRIPTION: Password manager for linux
#+AUTHOR: Linux-DEX
#+OPTIONS: toc:3

* TABLE OF CONTENT :toc:
- [[#password-manager][Password Manager]]
- [[#generate-gpg-key][Generate gpg-key]]
  - [[#to-view-the-gpg-key][To view the gpg key]]
  - [[#view-and-export-you-public-key][View and export you public key]]
- [[#pass-command][pass command]]
  - [[#initialize-password-store][Initialize Password Store]]
  - [[#insert-new-password][Insert New Password]]
  - [[#generate-a-new-password][Generate a New Password]]
  - [[#display-password][Display Password]]
  - [[#edit-password][Edit Password]]
  - [[#list-passwords][List Passwords]]
  - [[#decrypt-password][Decrypt password]]
  - [[#copy-password-to-clipboard][Copy Password to Clipboard]]
  - [[#generate-and-copy-a-password][Generate and copy a password]]
  - [[#find-password][Find Password]]
  - [[#remove-password][Remove Password]]
  - [[#sync-password-store][Sync Password Store]]
  - [[#insert-a-file-as-an-attachment][Insert a File as an Attachment]]
  - [[#backup-password-store][Backup Password Store]]
  - [[#initialize-git-repository-for-password-store][Initialize Git repository for password store]]
  - [[#show-password-tree][Show password tree]]
  - [[#import-passwords-from-another-password-manager][Import Passwords from another password manager]]

* Password Manager
=pass= is a command-line password manager for linux. It is designed to be simple, secure, and extensible. Here are some of the most important commands you can use with *pass*:

* Generate gpg-key
+ Run this command to generate the gpg key
#+begin_example
$ gpg --full-generate-key
#+end_example

+ Select the apropriate choose
+ Then enter the =name= and =email address= , and you can add comment to.
+ Then enter the passphrase to protect your new key.
+ that will generate the gpg key.
  
** To view the gpg key
#+begin_example
$ gpg --list-secret-keys --keyid-format LONG
#+end_example

** View and export you public key
#+begin_example
$ gpg --list-keys
#+end_example

#+begin_example
$ gpg --armor --export <your-email>
#+end_example

* pass command
** Initialize Password Store
Initializes the password store using GPG for encryption.

#+begin_example
$ pass init <gpg-key>
#+end_example

** Insert New Password
Adds a new password to the store.

#+begin_example
$ pass insert <path/to/password>
#+end_example

#+begin_example 
$ pass insert email/gmail
#+end_example

** Generate a New Password
Generates a new random password.

#+begin_example
$ pass generate <path/to/password> <length>
#+end_example

#+begin_example
$ pass generate social/twitter 16
#+end_example

** Display Password
Display the password for the specified entry.

#+begin_example
$ pass <path/to/password>
#+end_example

#+begin_example
$ pass email/gmail
#+end_example

** Edit Password
Edits the password for the specified entry.

#+begin_example
$ pass edit <path/to/password>
#+end_example

#+begin_example
$ pass edit social/twitter
#+end_example

** List Passwords
Lists all stored passwords.

#+begin_example
$ pass
#+end_example

** Decrypt password
#+begin_example
$ gpg -d facebook.com.gpg

or

$ gpg -d social/facebook.com.gpg
#+end_example

*then enter the /passphrase/ to unlock*.

** Copy Password to Clipboard
Copies the password to the clipboard.

#+begin_example
$ pass -c <path/to/password>
#+end_example

** Generate and copy a password
Generate and copies a new password to the clipboard.

#+begin_example
$ pass -c -n <path/to/password>
#+end_example

** Find Password
Search for passwords containing the specified term.

#+begin_example
$ pass find <search-term>
#+end_example

** Remove Password
Removes the specified password.

#+begin_example
$ pass rm <path/to/password>
#+end_example

** Sync Password Store
Pulls changes from the remote Git repository

#+begin_example
$ pass git pull
#+end_example

Pushes changes to the remote Git repository

#+begin_example
$ pass git push
#+end_example

** Insert a File as an Attachment
Inserts a file as an attachment to a password entry.

#+begin_example
$ pass insert -m <path/to/password> <file>
#+end_example

** Backup Password Store
Pushes changes to a remote Git repository

#+begin_example
$ pass git push origin master
#+end_example

** Initialize Git repository for password store
Initializes a Git repository for the password store.

#+begin_example
$ pass git init
#+end_example

** Show password tree
Display the password tree, showing the hierarchical structure of password.

#+begin_example
$ pass -t
#+end_example

** Import Passwords from another password manager
import password from another password manager.

#+begin_example
$ pass import <password-manager>
#+end_example
